version: "3.8"
services:
  php-apache-environment:
    image: detafebby/uas
    container_name: php-apache2
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - 8000:80
    networks:
      - backend

  db:
    container_name: db2
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ci_shop
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./toko-online-ci/ci_shop.sql:/docker-entrypoint-initdb.d/ci_shop.sql
    networks:
      - backend

volumes:
  db:

networks:
  backend:
    name: backend-network2
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24